### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ntthanh** [ibm-watson-iot/iot-csharp#17]
Hi,

Below is the prop.txt:
## Device Registration detail
Organization-ID=mol6gb
Device-Type=DotNETDevice
Device-ID=net-01
Authentication-Method=token
Authentication-Token=serialnumber-01
CA-Certificate-Path=G:\Company\SVN\Solutions\IOT\Broker\csharp\trunk\Demo\c\ca.crt
CA-Certificate-Password=
Client-Certificate-Path=G:\Company\SVN\Solutions\IOT\Broker\csharp\trunk\Demo\c\ad.p12
Client-Certificate-Password=1

We are trying to connect to the broker using Certificate-base authentication.  We follow this tuto to setup
https://www.ibm.com/developerworks/library/iot-trs-secure-iot-solutions1/index.html

The  only difference is that we do not use openssl to manage certificates, we use our Windows CA (1 level - There is no intermediate CA). And we use just one ROOT CA to:
a. issue service certificate;
b. certificates for devices;

The ROOT CA, Service Certificate (with correct common name and SAN - DNS, KU and EKU) has been uploaded correctly. 

problem is that your .net client could not connect to the broker. it causes an exception. 

using the same MQTT lib (M2MQTT), our sample also causes exception. The exception is:unable to read "data from the transport connection: an existing connection was forcibly closed by the remote host."

Could you please take a look at the issue?

Best,
Thanh

**Comment by hrhrprasath** [comment]
Hi Thanh,
Can you please tell me which .net version you are using?

**Comment by amitmangalvedkar** [comment]
@ntthanh : Could you please provide the environment and config details?

**Comment by ntthanh** [comment]
Hi,

I was able to connect to the MQTT without problem now using both SSL Client Auth and Token Auth, 

I have a mirror question about certificate validation: Does the backend validate certificate using OCSP? 

Best,
Thanh

**Comment by amitmangalvedkar** [comment]
@ntthanh : Watson IoT Platform does not support OCSP.   
The platform makes use of CRL for determining if an individual certificate has been revoked.  
In case your previous query, of connecting to the platform using TLS, is resolved, can we close this issue?

**Comment by amitmangalvedkar** [comment]
Closing this issue, @ntthanh can create a new issue for OCSP
