### ISSUE TITLE
How to control ports and protocol when connecting device?

### ISSUE THREAD

**Issue by xenod** [ibm-watson-iot/iot-csharp#18]
Hi,

I'm trying to use this sdk to connect a simple simulated C# device to bluemix. Corporate firewall requires that I use https and port 443.

How do I specify procol and port when using the DeviceClient-class?

Currently I have:
``` 
dc = new DeviceClient("XXX", "XXX", "XXX", "token", "XXX");
dc.connect();

...

 dc.publishEvent("event", "json", "{value:" + value + "}");
```

I have found no methods, properties or overloads that will allow me to change this?

Best regards,
Mikael

**Comment by hrhrprasath** [comment]
Hi Mikael,
By default DeviceClient use only MQTT protocol only.For MQTT you can set the port number as below
```
IBMWIoTP.AbstractClient.MQTTS_PORT = 443;

dc = new DeviceClient("XXX", "XXX", "XXX", "token", "XXX");
dc.connect();
```

**Comment by amitmangalvedkar** [comment]
@xenod : Are you ok with @hrhrprasath 's response? If yes, please close the issue.

**Comment by xenod** [comment]
Yes, thanks for your help!
