### ISSUE TITLE
Fix typo on ApplicationClient documentation

### ISSUE THREAD

**Issue by aledpardo** [ibm-watson-iot/iot-csharp#6]
I found a typo while reading the ApplicationClient documentation.

On Subscribe to Device Status, where we read:

``
applicationClient.subscribeToDeviceStatus += processDeviceStatus;
``

I supose it should be:

``
applicationClient.deviceStatusCallback += processDeviceStatus;
``

**Comment by hrhrprasath** [comment]
Updated in V0.2.1
