### ISSUE TITLE
Make a led blink on my device from c#

### ISSUE THREAD

**Issue by Iotbm01** [ibm-watson-iot/iot-csharp#7]
Hi guys,
I'm new on iot world.
I would like to send a command to a device (led blink or shutdown) from my c# software.
The device is registered (ibm watson platform). So know i don't really understand how i should do to make this work.

Let's see : (sampleAppClient.cs)

  class SampleAppClient
    {

        private static string orgId = "";
        private static string appId = "	";
        private static string apiKey = "";
        private static string authToken = "";

        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("test connect : " + appId);
                //string data = "name:foo,cpu:60,mem:50";
                string deviceType = "";
                string deviceId = "mbed01";
                string command = "blink";
                string format = "json";

                ApplicationClient applicationClient = new ApplicationClient(orgId, appId, apiKey, authToken);
                applicationClient.connect();

               /*
                Console.WriteLine("Connected sucessfully to app id : " + appId);

                applicationClient.commandCallback += processCommand;
                applicationClient.eventCallback += processEvent;
                applicationClient.deviceStatusCallback += processDeviceStatus;
                applicationClient.appStatusCallback += processAppStatus;

                applicationClient.subscribeToDeviceStatus();
                applicationClient.subscribeToApplicationStatus();
                 */

		applicationClient.publishCommand(deviceType, deviceId, command, format, data, 0);

                applicationClient.disconnect();
            }
            catch (Exception)
            {
                // ignore
            }
        }

So i don't understand what is the **appid** and i guess the **apikey** is the one i created but what is the "authtoken" ? the one with the api key or the one that was given when i did the device's registration?

And why do i need **data**? what should i put here ?
Finally, do i need to add something in another file?

Thanks for your answers and advices.

**Comment by Lokesh-K-Haralakatta** [comment]
Hi,

Thanks for writing to us, here are the answers to your questions:

**AppId:**  Unique Identifier for your application, say you can give as "sampleCSApp01"

**ApiKey and Auth Token:** This  pair you need to generate from Watson IoT Platform. From the Watson IoT Platform dashboard, go to Apps -> Generate API Key to get this pair.

**Command:** Actual command that you need to send to the device, in your case it may be **blink** or **Shutdown**

**Data:** It's data point value associated with the command. Say, you want to make device to blink led for 10 times at the intervals of every 2 seconds, then you need to build the payload accordingly and send. Example cmdData = { blinks : 10 , interval : 2 }

I hope these details help!

Thx,
Loki...

**Comment by Iotbm01** [comment]
Thanks for that quick answer,
So i did everything you said but it still doesn't work. 
Is there something to do about mqtt client ?

**Comment by Lokesh-K-Haralakatta** [comment]
Can you please provide the device client code along with the config details your are using? so that it will be easy to figure out the issue.

**Comment by Iotbm01** [comment]
Is there an email to send you my files?

**Comment by Lokesh-K-Haralakatta** [comment]
Please send across to lokesh.h.k@in.ibm.com, will get back to you by Monday.

**Comment by Iotbm01** [comment]
Ok thanks, i really appreciate the help.
I am going to do other tests and i will send you an email later or tomorrow.
See you soon.
